language: java

jdk:
  - oraclejdk8

install:
  - cd $TRAVIS_BUILD_DIR/maven-sdk3
  - mvn clean package
  - cd $TRAVIS_BUILD_DIR/maven-sdk4
  - mvn clean package
  - cd $TRAVIS_BUILD_DIR/gradle-with-plugin
  - ./gradlew clean assemble

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
