language: java

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f maven-sdk3/pom.xml
  - ./gradle-with-plugin/gradlew -b gradle-with-plugin/build.gradle assemble

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
